import Head from 'next/head';
import Header from '../components/Header';
import Login from '../components/Login';
import { getSession } from 'next-auth/react';

export default function Home({ session }) {
	if (!session) return <Login />;
	return (
		<div>
			<Head>
				<title>Facebook</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{/* header */}
				<Header />
				{/* sidebar */}
				{/* feed */}
			</main>
		</div>
	);
}

export async function getServerSideProps(context) {
	//get user
	const session = await getSession(context);
	return {
		props: {
			session,
		},
	};
}
